import { Labels } from 'eessi-pensjon-ui/dist/declarations/types.d'

export const dagerEnhet = {
  5: 'D/5 dager (5 dager i uken)',
  6: 'D/6 dager (6 dager i uken)',
  7: 'D/7 dager (7 dager i uken)'
} as Labels

export const type = {
  10: 'Pliktige avgiftsperioder',
  11: 'Pliktige avgiftsperioder - ansatt',
  12: 'Pliktige avgiftsperioder - selvstendig næringsdrivende',
  13: 'Pliktige avgiftsperioder - arbeidsledig',
  20: 'Frivillige avgiftsperioder',
  21: 'Frivillige avgiftsperioder - ansatt',
  22: 'Frivillige avgiftsperioder - selvstendig næringsdrivende',
  23: 'Frivillige avgiftsperioder - arbeidsledig',
  30: 'Bosettingsperioder',
  40: 'Likestilte perioder: uten nærmere spesifisering',
  41: 'Likestilte perioder: perioder med sykdom / arbeidsuførhet',
  42: 'Likestilte perioder: perioder med arbeidsledighet uten ytelser',
  43: 'Likestilte perioder: perioder med militærtjeneste',
  44: 'Likestilte perioder: perioder med opplæring eller utdanning',
  45: 'Likestilte perioder: perioder med omsorg for barn',
  46: 'Likestilte perioder: perioder med pensjon',
  47: 'Likestilte perioder: perioder med svangerskaps- eller fødselspermisjon',
  48: 'Likeverdige perioder: perioder med førtidspensjon',
  49: 'Likestilte perioder: perioder med arbeidsledighet med dagpenger',
  50: 'Likestilte perioder: periode hvor det er blitt iinnvilget uføretrygd',
  51: 'Likestilte perioder: perioder med omsorg for pleietrengende',
  52: 'Likevestilte perioder: fiktive perioder etter inntrådt uførhet, dødsdato eller start på pensjon'
}

export const relevantForYtelse = {
  '001': ' Kun for uførepensjon',
  '010': ' Kun for etterlattepensjon',
  '011': ' Kun for etterlatte- og uførepensjon',
  100: ' Kun for alderspensjon',
  101: ' Kun for alders- og uførepensjon',
  110: ' Kun for alders- og etterlattepensjon',
  111: ' Generell funksjon for alle pensjonsytelser (skal også brukes dersom det i nasjonal lovgivning ikke skilles mellom ulike pensjonsytelser)'
}

export const ordning = {
  '00': ' Generelt',
  '01': ' Ansettelsesforhold',
  '02': ' Selvstendig næringsvirksomhet',
  '03': ' Offentlig ansatt',
  '04': ' Gruvearbeider',
  '05': ' Botid',
  '06': ' Jordbrukere',
  '07': ' Sjømann (udefinert)',
  99: ' Annet'
}

export const yrke = {
  '0000': ' Yrke ukjent',
  '0001': ' Bergverk - gruvearbeider i dagbrudd',
  '0002': ' Bergverk - gruvearbeider under jorden',
  '0003': ' Bergverk - udefinert gruvearbeider',
  '0110': ' Militært befal på oppdrag',
  '0210': ' Militært befal uten oppdrag',
  '0310': ' Stillinger i forsvaret, andre grader',
  1111: ' Medlemmer av lovgivende forsamling',
  1112: ' Offentlig ansatt i høyere stilling',
  1113: ' Tradisjonelle overhoder, landsbyoverhoder',
  1114: ' Ansatte i høyere stilling i interesseorganisasjoner',
  1120: ' Administrerende direktører og toppledere',
  1211: ' Finansdirektører',
  1212: ' Personaldirektører',
  1213: ' Ledere innen policy and planning',
  1219: ' Ledere innen forretningstjenester og administrasjon uten annen klassifisering',
  1221: ' Ledere innen salg og markedsføring',
  1222: ' Ledere innen presse og kommunikasjon',
  1223: ' Ledere innen forskning og utvikling',
  1311: ' Ledere innen jord- og skogbruk',
  1312: ' Ledere innen havbruk og fiske',
  1321: ' Ledere innen produksjon',
  1322: ' Ledere innen gruvedrift',
  1323: ' Ledere i byggebransjen',
  1324: ' Ledere innen anskaffelser og distribusjon',
  1330: ' Ledere innen tjenesteyting i informasjons- og kommunikasjonsteknologi',
  1341: ' Ledere innen omsorgstjenester for barn',
  1342: ' Ledere i helsesektoren',
  1343: ' Ledere i eldreomsorgen',
  1344: ' Ledere i sosialsektoren',
  1345: ' Ledere i utdanningssektoren',
  1346: ' Avdelingsledere innen finans og forsikring',
  1349: ' Ledere innen profesjonsbaserte tjenester uten annen klassifisering',
  1411: ' Hotelldirektører',
  1412: ' Restaurantsjefer',
  1420: ' Ledere innen detalj- og grossisthandel',
  1431: ' Lederen for sports-, fritids- og kultursentre',
  1439: ' Ledere innen tjenesteyting uten annen klassifisering',
  2111: ' Fysikere og astronomer',
  2112: ' Meteorologer',
  2113: ' Kjemikere',
  2114: ' Geologer og geofysikere',
  2120: ' Matematikere, aktuarer og statistikere',
  2131: ' Biologer, botanikere, zoologer og tilknyttede profesjonsutøvere',
  2132: ' Rådgivere innen jordbruk, skogbruk og fiske',
  2133: ' Profesjonsutøvere innen miljøsektoren',
  2141: ' Ingeniører innen industri og produksjon',
  2142: ' Sivilingeniører',
  2143: ' Miljøingeniører',
  2144: ' Maskiningeniører',
  2145: ' Kjemiingeniører',
  2146: ' Gruveteknikere, metallurger og tilknyttede profesjonsutøvere',
  2149: ' Ingeniører uten annen klassifisering',
  2151: ' Elektroingeniører',
  2152: ' Elektronikkingeniører',
  2153: ' Telekommunikasjonsingeniører',
  2161: ' Bygningsarkitekter',
  2162: ' Landskapsarkitekter',
  2163: ' Produkt- og klesdesignere',
  2164: ' By- og trafikkplanleggere',
  2165: ' 2165 Kartografer og landmålere',
  2166: ' Grafiske designere og multimediedesignere',
  2211: ' Leger i allmennpraksis',
  2212: ' Leger i spesialistpraksis',
  2221: ' Pleiere i helsevesenet',
  2222: ' Jordmødre',
  2230: ' Tradisjonelle og alternative behandlere innen helse',
  2240: ' Førstehjelpspersonell',
  2250: ' Veterinærer',
  2261: ' Tannleger',
  2262: ' Farmasøyter',
  2263: ' Yrkesutøvere innen HMS-sektoren',
  2264: ' Fysioterapeuter',
  2265: ' 2265 Kostholdseksperter og ernæringsfysiologer',
  2266: ' Audiografer og talepedagoger',
  2267: ' Optometrikere og optikere',
  2269: ' Helsepersonell uten annen klassifisering',
  2310: ' Undervisningspersonell ved høyskoler og universitet',
  2320: ' Yrkesfaglærere',
  2330: ' Lærere i videregående skole',
  2341: ' Lærere i grunnskolen',
  2342: ' Barnehagelærere',
  2351: ' Spesialister i pedagogikk',
  2352: ' Spesiallærere',
  2353: ' Andre språklærere',
  2354: ' Andre musikklærere',
  2355: ' Andre kunstfaglærere',
  2356: ' Opplæringspersonell innen IT',
  2359: ' Utdanningspersonell uten annen klassifisering',
  2411: ' Regnskapsførere',
  2412: ' Finans- og investeringsrådgivere',
  2413: ' Finansanalytikere',
  2421: ' Ledelses- og organisasjonskonsulenter',
  2422: ' Profesjonsutøvere innen administrasjon og ledelse',
  2423: ' Profesjonsutøvere innen karriereutvikling',
  2424: ' Profesjonsutøvere innen opplærings- og personalutvikling',
  2431: ' Profesjonsutøvere innen reklame og markedsføring',
  2432: ' Profesjonsutøvere innen samfunnskontakt',
  2433: ' Profesjonsutøvere innen salg av teknikk og medisin (unntatt IKT)',
  2434: ' Ledere innen salg av informasjons- og kommunikasjonsteknologi',
  2511: ' Systemanalytikere',
  2512: ' Programvareutviklere',
  2513: ' Web- og multimedieutviklere',
  2514: ' Programmere av applikasjoner',
  2519: ' Utviklere av programvare og applikasjoner uten annen klassifisering',
  2521: ' Databasedesignere og administratorer',
  2522: ' Systemadministratorer',
  2523: ' Fagfolk innen datanettverk',
  2529: ' Fagfolk innen database og datanettverk uten annen klassifisering',
  2611: ' Advokater',
  2612: ' Dommere',
  2619: ' Profesjonsutøvere innen juss uten annen klassifisering',
  2621: ' Arkivarer og kuratorer',
  2622: ' Bibliotekarer og relaterte yrkesutøvere',
  2631: ' Økonomer',
  2632: ' Sosiologer, antropologer og relaterte yrkesutøvere',
  2633: ' Filosofer, historikere og statsvitere',
  2634: ' Psykologer',
  2635: ' Sosialarbeidere og -rådgivere',
  2636: ' Yrkesutøvere innen religiøs virksomhet',
  2641: ' Forfattere og relaterte skribenter',
  2642: ' Journalister',
  2643: ' Oversettere, tolker og andre lingvister',
  2651: ' Visuelle kunstnere',
  2652: ' Musikere, sangere og komponister',
  2653: ' Dansere og koreografer',
  2654: ' Regissører og produsere innen film og scenekunst',
  2655: ' Skuespillere',
  2656: ' Programannonsører på radio, TV og i andre medier',
  2659: ' Kreative og utøvende kunstnere uten annen klassifisering',
  3111: ' Teknikere innen kjemi og fysikk',
  3112: ' Teknikere innen bygg og anlegg',
  3113: ' Elektroteknikere',
  3114: ' Elektronikere',
  3115: ' Mekanikere',
  3116: ' Kjemiteknikere',
  3117: ' Teknikere innen gruvedrift og metallurgi',
  3118: ' Tekniske tegnere',
  3119: ' Teknikere inne fysikk og mekanikk uten annen klassifisering',
  3121: ' Arbeidsledere innen gruvedrift',
  3122: ' Arbeidsledere i industrien',
  3123: ' Arbeidsledere i bygg og anlegg',
  3131: ' Kraftstasjonsoperatører',
  3132: ' Operatører på forbrennings- og vannrenseanlegg',
  3133: ' Kontrollere i kjemisk prosessindustri',
  3134: ' Operatører ved olje- og gassraffinerier',
  3135: ' Kontrollere i metallindustrien',
  3139: ' Teknikere innen prosesskontroll uten annen klassifisering',
  3141: ' Lærere innen livsvitenskapene (unntatt medisin)',
  3142: ' Landbruksteknikere',
  3143: ' Skogbruksteknikere',
  3151: ' Skipsingeniører',
  3152: ' Dekksoffiserer på skip og loser',
  3153: ' Flygere og relaterte yrkesutøvere',
  3154: ' Flygeledere',
  3155: ' Elektronikere innen flysikkerhet',
  3211: ' Teknikere innen medisinsk avbildning og behandlingsutstyr',
  3212: ' Laboratorieteknikere innen medisin og patologi',
  3213: ' Apotekteknikere og -assistenter',
  3214: ' Medisinske teknikere og proteseteknikere',
  3221: ' Pleiemedhjelpere',
  3222: ' Medhjelpere innen jordmorfaget',
  3230: ' Assistenter til tradisjonelle og alternative behandlere innen helse',
  3240: ' Veterinærteknikere og -assistenter',
  3251: ' Tannlegeassistenter og tannterapeuter',
  3252: ' Teknikere ved helsearkiver og innen helseinformatikk',
  3253: ' Helsearbeidere i lokalmiljøet',
  3254: ' Selgere i optikerbransjen',
  3255: ' Fysioterapiteknikere og -assistenter',
  3256: ' Helseassistenter',
  3257: ' Inspektører og medarbeidere i HMS-sektoren',
  3258: ' Ambulansearbeider',
  3259: ' Helsemedarbeidere uten annen klassifisering',
  3311: ' Verdipapir- og finansmeglere',
  3312: ' Ansatte innen kreditt og långiving',
  3313: ' Regnskapsmedarbeidere',
  3314: ' Medarbeidere innen statistikk, matematikk og relaterte yrker',
  3315: ' Takstmenn og tapsanalytikere',
  3321: ' Forsikringsrepresentanter',
  3322: ' Salgsrepresentanter',
  3323: ' Innkjøpere',
  3324: ' Handelsmeglere',
  3331: ' Clearing-representanter og speditører',
  3332: ' Konferanse- og arrangementplanleggere',
  3333: ' Representanter innen bemanning og kontrahering av arbeidstakere',
  3334: ' Eiendomsmeglere og eiendomsforvaltere',
  3339: ' Yrkesutøvere innen forretningstjenester uten annen klassifisering',
  3341: ' Kontorledere',
  3342: ' Advokatsekretærer',
  3343: ' Administrasjons- og ledersekretærer',
  3344: ' Legesekretærer',
  3351: ' Toll- og grenseinspektører',
  3352: ' Medarbeidere i offentlig skatte- og avgiftsmyndighet',
  3353: ' Medarbeidere i offentlig sosialmyndighet',
  3354: ' Medarbeidere i offentlig, bevilgende myndighet',
  3355: ' Politibetjenter og -etterforskere',
  3359: ' Medarbeidere i offentlig, regulerende myndighet uten annen klassifisering',
  3411: ' Medarbeidere innen juridiske og relaterte yrker',
  3412: ' Medarbeidere i sosialsektoren',
  3413: ' Medarbeidere innen religionsutøvelse',
  3421: ' Idrettsutøvere og lagidrettsutøvere',
  3422: ' Idrettstrenere, idrettsinstruktører og idrettsfunksjonærer',
  3423: ' Instruktører og programansvarlige innen trenings- og fritidsaktiviteter',
  3431: ' Fotografer',
  3432: ' Interiørdesignere og dekoratører',
  3433: ' Teknikere på gallerier, museer og biblioteker',
  3434: ' Kjøkkensjefer',
  3435: ' Andre medarbeidere innen kunst og kultur',
  3511: ' Fagoperatører innen informasjons- og kommunikasjonsteknologi',
  3512: ' Fagoperatører innen informasjons- og kommunikasjonsteknologi',
  3513: ' Systemteknikere innen datanettverk',
  3514: ' Web-teknikere',
  3521: ' Teknikere innen kringkasting, lyd og bilde',
  3522: ' Telekommunikasjonsteknikere',
  4110: ' Kontormedarbeidere',
  4120: ' Sekretærer (generelt)',
  4131: ' Fagoperatører innen skrive- og tekstarbeid',
  4132: ' Datainnleggere',
  4211: ' Bankkasserer og relaterte kontormedarbeidere',
  4212: ' Bookmakere, croupierer og relaterte arbeidere i spillbransjen',
  4213: ' Pantelånere og pengeutlånere',
  4214: ' Pengeinnkrevere og relaterte arbeidere',
  4221: ' Konsulenter og kontormedarbeidere i reiselivet',
  4222: ' Informasjonskonsulenter på kontaktsentre',
  4223: ' Operatører i telefonsentraler',
  4224: ' Hotellresepsjonister',
  4225: ' Medarbeidere innen spørreundersøkelser',
  4226: ' Resepsjonister (generelt)',
  4227: ' Intervjuere innen spørreundersøkelser og markedsundersøkelser',
  4229: ' Medarbeidere innen kundeopplysning uten annen klassifisering',
  4311: ' Kontormedarbeidere innen regnskap og bokføring',
  4312: ' Kontormedarbeidere innen statistikk, finans og forsikring',
  4313: ' Lønnsmedarbeidere',
  4321: ' Lagermedarbeidere',
  4322: ' Produksjonsmedarbeidere',
  4323: ' Transportmedarbeidere',
  4411: ' Bibliotekmedarbeidere',
  4412: ' Postbud og postsorterere',
  4413: ' Kontormedarbeidere innen koding, korrekturlesing og relatert virksomhet',
  4414: ' Skribenter og relaterte arbeidere',
  4415: ' Kontormedarbeidere innen arkivering og kopiering',
  4416: ' Personalmedarbeidere',
  4419: ' Medarbeidere innen kontorstøtte uten annen klassifisering',
  5111: ' Reiseledere og stewarder',
  5112: ' Konduktører i transportsektoren',
  5113: ' Reiseguider',
  5120: ' Kokker',
  5131: ' Kelnere',
  5132: ' Bartendere',
  5141: ' Frisører',
  5142: ' Stylister og relaterte arbeidere',
  5151: ' Medarbeidere innen rengjøring og husholdning på kontorer, hoteller og andre virkskomheter',
  5152: ' Hjemmehusholdere/-husholdersker',
  5153: ' Vaktmestere for bygninger',
  5161: ' Astrologer, spåkoner, spåmenn og relaterte arbeidere',
  5162: ' Ledsagere og tjenere',
  5163: ' Begravelsesagenter og likstellere',
  5164: ' Medarbeidere innen dyrestell og dyrevelferd',
  5165: ' Kjørelærere',
  5169: ' Medarbeidere innen personalstøtte uten annen klassifisering',
  5211: ' Kioskansatte og markedsselgere',
  5212: ' Medarbeidere på gatekjøkken',
  5221: ' Butikkeiere',
  5222: ' Butikkledere',
  5223: ' Butikkmedarbeidere',
  5230: ' Kassamedarbeidere og billettselgere',
  5241: ' Modeller i motebransjen og andre modeller',
  5242: ' Demonstratører innen salg',
  5243: ' Dørselgere',
  5244: ' Salgsmedarbeidere på kontaktsentre',
  5245: ' Bensinstasjonsmedarbeidere',
  5246: ' Kafeteriamedarbeidere',
  5249: ' Salgsmedarbeidere uten annen klassifisering',
  5311: ' Arbeidere innen omsorgstjenester for barn',
  5312: ' Lærerassistenter',
  5321: ' Pleieassistenter',
  5322: ' Medarbeidere i hjemmeomsorg',
  5329: ' Omsorgsarbeidere uten annen klassifisering',
  5411: ' Brannmannskap',
  5412: ' Politibetjenter',
  5413: ' Fengselsvakter',
  5414: ' Sikkerhetsvakter',
  5419: ' Medarbeidere innen sikkerhet uten annen klassifisering',
  6111: ' Åker- og grønnsakdyrkere',
  6112: ' Jordbrukere innen bær og frukt',
  6113: ' Gartnere, hagebrukere og arbeidere på hagesentre',
  6114: ' Dyrkere av ulike vekster',
  6121: ' Husdyrbønder og melkeprodusenter',
  6122: ' Hønsefarmere',
  6123: ' Birøktere og silkedyrkere',
  6129: ' Husdyrprodusenter uten annen klassifisering',
  6130: ' Kombinerte landbrukere innen jorddyrking og husdyrhold',
  6210: ' Skogsarbeidere og relaterte arbeidere',
  6221: ' Arbeidere innen fiskeoppdrett',
  6222: ' Innlands- og kystfiskere',
  6223: ' Dyphavsfiskere',
  6224: ' Jegere og fangstmenn',
  6310: ' Kornbønder innen selvberging',
  6320: ' Husdyrbønder innen selvberging',
  6330: ' Kombinerte korn- og husdyrbønder innen selvberging',
  6340: ' Fiskere, jegere fangstfolk og samlere for selvberging',
  7111: ' Boligbyggere',
  7112: ' Murere og relaterte arbeidere',
  7113: ' Steinhuggere',
  7114: ' Betongarbeidere og relaterte arbeidere',
  7115: ' Snekkere og tømrere',
  7119: ' Bygningsarbeidere innen reisverk og relaterte arbeidere uten annen klassifisering',
  7121: ' Taktekkere',
  7122: ' Gulv- og flisleggere',
  7123: ' Gipsarbeidere',
  7124: ' Arbeidere innen varmeisolering',
  7125: ' Glassmestere',
  7126: ' Rørleggere',
  7127: ' Teknikere innen klimaanlegg og kjøleanlegg',
  7131: ' Malere og relaterte arbeidere',
  7132: ' Sprøytelakkerere og lakkeringsarbeidere',
  7133: ' Bygningsrenholdere',
  7211: ' Metallstøpere og kjernemakere',
  7212: ' 7212 Sveisere og arbeidere innen skjærebrenning',
  7213: ' Blikkenslagere',
  7214: ' Bygningsmontører for metallstrukturer',
  7215: ' Arbeidere innen rigging og kabelskjøting',
  7221: ' Smeder, hammersmeder og slagpressearbeidere',
  7222: ' Verktøymakere og relaterte arbeidere',
  7223: ' Operatører og oppstillere av verktøy for bearbeiding av metall',
  7224: ' Arbeidere innen polering og sliping av metall',
  7231: ' Mekanikere og reparatører for kjøretøy',
  7232: ' Mekanikere og reparatører for fly',
  7233: ' Mekanikere og reparatører for jordbruks- og industrimaskiner',
  7234: ' Sykkelreparatører og relaterte virksomhet',
  7311: ' Verktøymakere og reparatører av presisjonsverktøy',
  7312: ' Instrumentmakere og stemmere for musikkinstrumenter',
  7313: ' Juvelerer, gull- og sølvsmeder',
  7314: ' Pottemakere og relaterte arbeidere',
  7315: ' Glassblåsere, glasskjærere og glasshåndverkere',
  7316: ' Skiltmalere, dekoratører og gravører',
  7317: ' Kunsthåndverkere innen treskjæring og kurvfletting',
  7318: ' Kunsthåndverkere innen tekstil, lær og relaterte materialer',
  7319: ' Kunsthåndverkere uten annen klassifisering',
  7321: ' Førtrykksteknikere',
  7322: ' Trykkeriarbeidere',
  7323: ' Fagarbeidere innen fremstilling av trykksaker og bokbindere',
  7411: ' Bygningselektrikere og relaterte yrker',
  7412: ' Elektroteknikere og -montører',
  7413: ' Elverksmontører og -reparatører',
  7421: ' Elektroteknikere og elektroreparatører',
  7422: ' Installatører og servicepersonell innen informasjons- og kommunikasjonsteknologi',
  7511: ' Slaktere, fiskehandlere og relaterte tilberedere av matvarer',
  7512: ' Bakere og konditorer',
  7513: ' Fabrikanter av meieriprodukter',
  7514: ' Arbeidere innen konservering av frukt og grønnsaker',
  7515: ' Testere og prøvesmakere av mat- og drikkevarer',
  7516: ' Tobakksarbeidere og -fabrikanter',
  7521: ' Trevarebehandlere',
  7522: ' Møbelsnekkere og relaterte arbeidere',
  7523: ' Operatører og oppstillere av verktøy for bearbeiding av trevarer',
  7531: ' Skreddere, buntmakere og hattemakere',
  7532: ' Tilskjærere innen tekstilindustrien',
  7533: ' Arbeidere innen sying, brodering og relaterte arbeidere',
  7534: ' Møbeltapetserer og relaterte arbeidere',
  7535: ' Garvere og arbeidere innen bearbeiding av pels og skinn',
  7536: ' Skomakere og relaterte arbeidere',
  7541: ' Dykkere',
  7542: ' Skytebaser og sprengningsbaser',
  7543: ' Produkttestere (unntatt mat og drikke)',
  7544: ' Desinfektører, andre skadedyrkontrollører og plantevernere',
  7549: ' Håndverkere og relaterte arbeidere uten annen klassifisering',
  8111: ' Arbeidere i gruver og steinbrudd',
  8112: ' Operatører på bearbeidingsanlegg for mineraler og stein',
  8113: ' Brønnborere, borearbeidere og relaterte arbeidere',
  8114: ' Operatører av maskiner innen sement, stein og mineralproduksjon',
  8121: ' Operatører metallurgisk industri',
  8122: ' Operatører innen bearbeiding og overflatebehandling av metall',
  8131: ' Maskinoperatører i kjemikalieproduksjon',
  8132: ' Maskinoperatører i fotografisk produksjon',
  8141: ' Maskinoperatører i gummiproduksjon',
  8142: ' Maskinoperatører i plastproduksjon',
  8143: ' Maskinoperatører i papirproduksjon',
  8151: ' Maskinoperatører innen bearbeiding av fibre og tekstiler',
  8152: ' Maskinoperatører i veving og strikking',
  8153: ' Symaskinoperatører',
  8154: ' Maskinoperatører innen bleking, farging og rengjøring av tekstiler',
  8155: ' Maskinoperatører innen bearbeiding av pels og skinn',
  8156: ' Maskinoperatører i skoproduksjon',
  8157: ' Vaskemaskinoperatører',
  8159: ' Maskinoperatører innen tekstil, pels og skinn uten annen klassifisering',
  8160: ' Maskinoperatører i matvareproduksjon og relaterte produkter',
  8171: ' Maskinoperatører i papirfabrikker',
  8172: ' Maskinoperatører i treforedlingsindustri',
  8181: ' Maskinoperatører på glass- og keramikkfabrikker',
  8182: ' Operatører ved dampmaskiner og kjeleanlegg',
  8183: ' Maskinoperatører ved pakke-, flaskefylling og merkemaskiner',
  8189: ' Operatører av stasjonære anlegg og maskiner uten annen klassifisering',
  8211: ' Montører av mekaniske utstyr',
  8212: ' Montører av elektrisk og elektronisk utstyr',
  8219: ' Montører uten annen klassifisering',
  8311: ' Lokomotivførere',
  8312: ' Signalmontører og operatører ved jernbane',
  8321: ' Motorsykkelsjåfører',
  8322: ' Sjåfører og taxi- og varetaxisjåfører',
  8331: ' Buss- og trikkesjåfører',
  8332: ' Lastebil- og trailersjåfører',
  8341: ' Maskinoperatører på mobilt utstyr i land- og skogbruk',
  8342: ' Maskinoperatører på bulldosere og relatert utstyr',
  8343: ' Maskinoperatører på kraner, heisekraner og relatert utstyr',
  8344: ' Operatører på gaffeltruck',
  8350: ' Dekkmannskap på skip og relaterte arbeidere',
  9111: ' Rengjøringsarbeidere i hjemmet',
  9112: ' Rengjøringsarbeidere på kontorer, hoteller og andre virksomheter',
  9121: ' Vaskeri- og renseriarbeidere',
  9122: ' Rengjørere av kjøretøy',
  9123: ' Vindusvaskere',
  9129: ' Andre rengjøringsmedarbeidere',
  9211: ' Kroppsarbeidere innen jorddyrking',
  9212: ' Kroppsarbeidere innen husdyrhold',
  9213: ' Kombinerte kroppsarbeidere innen jorddyrking og husdyrhold',
  9214: ' Kroppsarbeidere innen hagebruk',
  9215: ' Kroppsarbeidere i skogbruk',
  9216: ' Kroppsarbeidere innen fiske og fiskeoppdrettsanlegg',
  9311: ' Kroppsarbeidere i gruver og steinbrudd',
  9312: ' Kroppsarbeidere innen bygg og anlegg',
  9313: ' Kroppsarbeidere i byggebransjen',
  9321: ' Pakkemedarbeidere',
  9329: ' Produksjonsmedarbeidere uten annen klassifisering',
  9331: ' Førere av hånddrevne og pedaldrevne kjøretøy',
  9332: ' Førere av kjøretøy og maskineri drevet av dyr',
  9333: ' Fraktmedarbeidere',
  9334: ' Hyllemedarbeidere',
  9411: ' Medarbeidere innen tilberedning av ferdigmat',
  9412: ' Kjøkkenmedhjelpere',
  9510: ' Arbeidere innen gatetjenester og relaterte yrker',
  9520: ' Gateselgere (unntatt mat)',
  9611: ' Søppeltømmere og medarbeidere innen gjenbruk',
  9612: ' Avfallssorterere',
  9613: ' Gatefeiere og relaterte kroppsarbeidere',
  9621: ' Bud, pakkeekspeditører og bærere',
  9622: ' Dagarbeidere',
  9623: ' Avlesere av måleapparater og kontrollører av salgsautomater',
  9624: ' Kroppsarbeidere innen henting av vann og brensel',
  9629: ' Kroppsarbeidere uten annen klassifisering'
}

export const informasjonOmBeregning = {
  '000': ' Ingen funksjon',
  '001': ' Kun for uførepensjon',
  '010': ' Kun for etterlattepensjon',
  '011': ' Kun for etterlatte- og uførepensjon',
  100: ' Kun for alderspensjon',
  101: ' Kun for alders- og uførepensjon',
  110: ' Kun for alders- og etterlattepensjon',
  111: ' Generell funksjon for alle pensjonsytelser (skal også brukes dersom det i nasjonal lovgivning ikke skilles mellom ulike pensjonsytelser)'
}
