server:
    port: 8080

app:
  name: 'FRONT-DEVELOP'
  version: '0.1'

freg:
  security:
    oidc:
      ignored-paths: '/internal/**,/error**'
      refresh:
        enabled: 'true'
      auth:
        header-filter-enabled: 'false'
        cookie-filter-enabled: 'true'
      login:
        enabled: 'true'
        path: '/login/oauth2/code/openam'
      openam:
        url: 'https://isso-t.adeo.no:443/isso'
      client-id: 'eessi-fagmodul-localhost'
      client-secret: '${OPENAM_SECRET}'

credential:
  username: '${SRVPENSJON_USERNAME}'
  password: '${SRVPENSJON_PASSWORD}'

eessibasis:
#  url: 'https://eux-app.nais.preprod.local'
# url: 'https://eux-app-t8.nais.preprod.local'
 url: 'http://localhost:9090'

fagmodul:
#  url: 'https://eessi-fagmodul.nais.preprod.local'
#  url: 'https://eessi-fagmodul-t8.nais.preprod.local'
  url: 'http://localhost:8081'

rina:
   url: "http://rina-oppl-utv004.adeo.no/portal/#/caseManagement/"