FROM repo.adeo.no:5443/pus/decorator:228.20190926.1521
ENV APPLICATION_NAME=eessipen
ENV PUBLIC_ZONE=fss
ENV DISABLE_FRONTEND_LOGGER=true
ENV DISABLE_DECORATOR=true
ENV DISABLE_UNLEASH=true
ENV CONTEXT_PATH=/
COPY /build /app
ADD decorator.yaml /decorator.yaml
