FROM repo.adeo.no:5443/pus/decorator:156.20181221.0926
ENV APPLICATION_NAME=eessipen
ENV PUBLIC_ZONE=sbs
ENV CONTEXT_PATH /
ENV DISABLE_FRONTEND_LOGGER true
ADD build /app
ADD proxy_sbs.json /proxy.json