export const SERVER_OFFLINE = 'SERVER/OFFLINE';

export const LANGUAGE_CHANGED = 'LANGUAGE/CHANGED';

export const USERCASE_GET_CASE_SUCCESS = 'USERCASE/GET_CASE_SUCCESS';
export const USERCASE_GET_CASE_REQUEST = 'USERCASE/GET_CASE_REQUEST';
export const USERCASE_GET_CASE_FAILURE = 'USERCASE/GET_CASE_FAILURE';

export const USERCASE_GET_SUBJECT_AREA_LIST_SUCCESS = 'USERCASE/GET_SUBJECT_AREA_LIST_SUCCESS';
export const USERCASE_GET_SUBJECT_AREA_LIST_REQUEST = 'USERCASE/GET_SUBJECT_AREA_LIST_REQUEST';
export const USERCASE_GET_SUBJECT_AREA_LIST_FAILURE = 'USERCASE/GET_SUBJECT_AREA_LIST_FAILURE';

export const USERCASE_GET_INSTITUTION_LIST_SUCCESS = 'USERCASE/GET_INSTITUTION_LIST_SUCCESS';
export const USERCASE_GET_INSTITUTION_LIST_REQUEST = 'USERCASE/GET_INSTITUTION_LIST_REQUEST';
export const USERCASE_GET_INSTITUTION_LIST_FAILURE = 'USERCASE/GET_INSTITUTION_LIST_FAILURE';

export const USERCASE_GET_BUC_LIST_SUCCESS = 'USERCASE/GET_BUC_LIST_SUCCESS';
export const USERCASE_GET_BUC_LIST_REQUEST = 'USERCASE/GET_BUC_LIST_REQUEST';
export const USERCASE_GET_BUC_LIST_FAILURE = 'USERCASE/GET_BUC_LIST_FAILURE';

export const USERCASE_GET_SED_LIST_SUCCESS = 'USERCASE/GET_SED_LIST_SUCCESS';
export const USERCASE_GET_SED_LIST_REQUEST = 'USERCASE/GET_SED_LIST_REQUEST';
export const USERCASE_GET_SED_LIST_FAILURE = 'USERCASE/GET_SED_LIST_FAILURE';

export const USERCASE_GET_COUNTRY_LIST_SUCCESS = 'USERCASE/GET_COUNTRY_LIST_SUCCESS';
export const USERCASE_GET_COUNTRY_LIST_REQUEST = 'USERCASE/GET_COUNTRY_LIST_REQUEST';
export const USERCASE_GET_COUNTRY_LIST_FAILURE = 'USERCASE/GET_COUNTRY_LIST_FAILURE';

export const USERCASE_DATA_TO_GENERATE_SUCCESS = 'USERCASE/DATA_TO_GENERATE_SUCCESS';
export const USERCASE_DATA_TO_GENERATE_REQUEST = 'USERCASE/DATA_TO_GENERATE_REQUEST';
export const USERCASE_DATA_TO_GENERATE_FAILURE = 'USERCASE/DATA_TO_GENERATE_FAILURE';

export const USERCASE_DATA_TO_CONFIRM_SUCCESS = 'USERCASE/DATA_TO_CONFIRM_SUCCESS';

export const NAVIGATION_FORWARD = 'NAVIGATION/FORWARD';
export const NAVIGATION_BACK    = 'NAVIGATION/BACK';

export const USERCASE_POST_SUCCESS = 'USERCASE/POST_SUCCESS';
export const USERCASE_POST_REQUEST = 'USERCASE/POST_REQUEST';
export const USERCASE_POST_FAILURE = 'USERCASE/POST_FAILURE';

export const GET_RINA_URL_SUCCESS = 'GET_RINA_URL_SUCCESS';
export const GET_RINA_URL_REQUEST = 'GET_RINA_URL_REQUEST';
export const GET_RINA_URL_FAILURE = 'GET_RINA_URL_FAILURE';
