export const SERVER_OFFLINE = 'SERVER/OFFLINE';

export const LANGUAGE_CHANGED = 'LANGUAGE/CHANGED';

export const NAVIGATION_FORWARD = 'NAVIGATION/FORWARD';
export const NAVIGATION_BACK    = 'NAVIGATION/BACK';

export const USERCASE_GET_CASE_NUMBER_SUCCESS = 'USERCASE/GET_CASE_NUMBER/SUCCESS';
export const USERCASE_GET_CASE_NUMBER_REQUEST = 'USERCASE/GET_CASE_NUMBER/REQUEST';
export const USERCASE_GET_CASE_NUMBER_FAILURE = 'USERCASE/GET_CASE_NUMBER/FAILURE';

export const USERCASE_GET_SUBJECT_AREA_LIST_SUCCESS = 'USERCASE/GET_SUBJECT_AREA_LIST/SUCCESS';
export const USERCASE_GET_SUBJECT_AREA_LIST_REQUEST = 'USERCASE/GET_SUBJECT_AREA_LIST/REQUEST';
export const USERCASE_GET_SUBJECT_AREA_LIST_FAILURE = 'USERCASE/GET_SUBJECT_AREA_LIST/FAILURE';

export const USERCASE_GET_INSTITUTION_LIST_SUCCESS = 'USERCASE/GET_INSTITUTION_LIST/SUCCESS';
export const USERCASE_GET_INSTITUTION_LIST_REQUEST = 'USERCASE/GET_INSTITUTION_LIST/REQUEST';
export const USERCASE_GET_INSTITUTION_LIST_FAILURE = 'USERCASE/GET_INSTITUTION_LIST/FAILURE';

export const USERCASE_GET_BUC_LIST_SUCCESS = 'USERCASE/GET_BUC_LIST/SUCCESS';
export const USERCASE_GET_BUC_LIST_REQUEST = 'USERCASE/GET_BUC_LIST/REQUEST';
export const USERCASE_GET_BUC_LIST_FAILURE = 'USERCASE/GET_BUC_LIST/FAILURE';

export const USERCASE_GET_SED_LIST_SUCCESS = 'USERCASE/GET_SED_LIST/SUCCESS';
export const USERCASE_GET_SED_LIST_REQUEST = 'USERCASE/GET_SED_LIST/REQUEST';
export const USERCASE_GET_SED_LIST_FAILURE = 'USERCASE/GET_SED_LIST/FAILURE';

export const USERCASE_GET_COUNTRY_LIST_SUCCESS = 'USERCASE/GET_COUNTRY_LIST/SUCCESS';
export const USERCASE_GET_COUNTRY_LIST_REQUEST = 'USERCASE/GET_COUNTRY_LIST/REQUEST';
export const USERCASE_GET_COUNTRY_LIST_FAILURE = 'USERCASE/GET_COUNTRY_LIST/FAILURE';

export const USERCASE_GENERATE_DATA_SUCCESS = 'USERCASE/GENERATE_DATA/SUCCESS';
export const USERCASE_GENERATE_DATA_REQUEST = 'USERCASE/GENERATE_DATA/REQUEST';
export const USERCASE_GENERATE_DATA_FAILURE = 'USERCASE/GENERATE_DATA/FAILURE';

export const USERCASE_CONFIRM_DATA_SUCCESS = 'USERCASE/CONFIRM_DATA/SUCCESS';
export const USERCASE_CLEAR_DATA           = 'USERCASE/CLEAR_DATA';
export const USERCASE_CLEAR_CURRENT_CASE   = 'USERCASE/CLEAR_CURRENT_CASE';

export const USERCASE_SEND_DATA_SUCCESS = 'USERCASE/SEND_DATA/SUCCESS';
export const USERCASE_SEND_DATA_REQUEST = 'USERCASE/SEND_DATA/REQUEST';
export const USERCASE_SEND_DATA_FAILURE = 'USERCASE/SEND_DATA/FAILURE';

export const RINA_GET_URL_SUCCESS = 'RINA/GET_URL/SUCCESS';
export const RINA_GET_URL_REQUEST = 'RINA/GET_URL/REQUEST';
export const RINA_GET_URL_FAILURE = 'RINA/GET_URL/FAILURE';

export const USER_INFO_REQUEST = 'USER/INFO/REQUEST';
export const USER_INFO_SUCCESS = 'USER/INFO/SUCCESS';
export const USER_INFO_FAILURE = 'USER/INFO/FAILURE';

export const PDF_CLEAR            = 'PDF/CLEAR';
export const PDF_SELECTED         = 'PDF/SELECTED';
export const PDF_GENERATE_REQUEST = 'PDF/GENERATE/REQUEST';
export const PDF_GENERATE_SUCCESS = 'PDF/GENERATE/SUCCESS';
export const PDF_GENERATE_FAILURE = 'PDF/GENERATE/FAILURE';

export const PDF_SET_RECIPE       = 'PDF/SET_RECIPE';
export const PDF_PREVIEW_START    = 'PDF/PREVIEW/START';
export const PDF_PREVIEW_END      = 'PDF/PREVIEW/END';

export const SETTINGS_SET_PDF_SIZE = 'SETTINGS/SET_PDF_SIZE'
