export const SERVER_OFFLINE = 'SERVER/OFFLINE';

export const LANGUAGE_CHANGED = 'LANGUAGE/CHANGED';

export const NAVIGATION_FORWARD = 'NAVIGATION/FORWARD';
export const NAVIGATION_BACK    = 'NAVIGATION/BACK';

export const UI_MODAL_OPEN  = 'UI/MODAL/OPEN';
export const UI_MODAL_CLOSE = 'UI/MODAL/CLOSE';

export const ALERT_CLIENT_CLEAR = 'ALERT/CLIENT/CLEAR';

export const STATUS_GET_SUCCESS = 'STATUS/GET/SUCCESS';
export const STATUS_GET_REQUEST = 'STATUS/GET/REQUEST';
export const STATUS_GET_FAILURE = 'STATUS/GET/FAILURE';

export const USERCASE_NULL = 'USERCASE/NULL';

export const USERCASE_GET_CASE_NUMBER_SUCCESS = 'USERCASE/GET_CASE_NUMBER/SUCCESS';
export const USERCASE_GET_CASE_NUMBER_REQUEST = 'USERCASE/GET_CASE_NUMBER/REQUEST';
export const USERCASE_GET_CASE_NUMBER_FAILURE = 'USERCASE/GET_CASE_NUMBER/FAILURE';

export const USERCASE_GET_SUBJECT_AREA_LIST_SUCCESS = 'USERCASE/GET_SUBJECT_AREA_LIST/SUCCESS';
export const USERCASE_GET_SUBJECT_AREA_LIST_REQUEST = 'USERCASE/GET_SUBJECT_AREA_LIST/REQUEST';
export const USERCASE_GET_SUBJECT_AREA_LIST_FAILURE = 'USERCASE/GET_SUBJECT_AREA_LIST/FAILURE';

export const USERCASE_GET_INSTITUTION_LIST_SUCCESS = 'USERCASE/GET_INSTITUTION_LIST/SUCCESS';
export const USERCASE_GET_INSTITUTION_LIST_REQUEST = 'USERCASE/GET_INSTITUTION_LIST/REQUEST';
export const USERCASE_GET_INSTITUTION_LIST_FAILURE = 'USERCASE/GET_INSTITUTION_LIST/FAILURE';

export const USERCASE_GET_BUC_LIST_SUCCESS = 'USERCASE/GET_BUC_LIST/SUCCESS';
export const USERCASE_GET_BUC_LIST_REQUEST = 'USERCASE/GET_BUC_LIST/REQUEST';
export const USERCASE_GET_BUC_LIST_FAILURE = 'USERCASE/GET_BUC_LIST/FAILURE';

export const USERCASE_GET_SED_LIST_SUCCESS = 'USERCASE/GET_SED_LIST/SUCCESS';
export const USERCASE_GET_SED_LIST_REQUEST = 'USERCASE/GET_SED_LIST/REQUEST';
export const USERCASE_GET_SED_LIST_FAILURE = 'USERCASE/GET_SED_LIST/FAILURE';

export const USERCASE_GET_COUNTRY_LIST_SUCCESS = 'USERCASE/GET_COUNTRY_LIST/SUCCESS';
export const USERCASE_GET_COUNTRY_LIST_REQUEST = 'USERCASE/GET_COUNTRY_LIST/REQUEST';
export const USERCASE_GET_COUNTRY_LIST_FAILURE = 'USERCASE/GET_COUNTRY_LIST/FAILURE';

export const USERCASE_GENERATE_DATA_SUCCESS = 'USERCASE/GENERATE_DATA/SUCCESS';
export const USERCASE_GENERATE_DATA_REQUEST = 'USERCASE/GENERATE_DATA/REQUEST';
export const USERCASE_GENERATE_DATA_FAILURE = 'USERCASE/GENERATE_DATA/FAILURE';

export const USERCASE_CONFIRM_DATA_SUCCESS = 'USERCASE/CONFIRM_DATA/SUCCESS';

export const USERCASE_CLEAR_DATA          = 'USERCASE/CLEAR_DATA';
export const USERCASE_CLEAR_CURRENT_CASE  = 'USERCASE/CLEAR_CURRENT_CASE';

export const USERCASE_CREATE_SED_SUCCESS = 'USERCASE/CREATE_SED/SUCCESS';
export const USERCASE_CREATE_SED_REQUEST = 'USERCASE/CREATE_SED/REQUEST';
export const USERCASE_CREATE_SED_FAILURE = 'USERCASE/CREATE_SED/FAILURE';

export const USERCASE_ADD_TO_SED_SUCCESS = 'USERCASE/ADD_TO_SED/SUCCESS';
export const USERCASE_ADD_TO_SED_REQUEST = 'USERCASE/ADD_TO_SED/REQUEST';
export const USERCASE_ADD_TO_SED_FAILURE = 'USERCASE/ADD_TO_SED/FAILURE';

export const USERCASE_SEND_SED_SUCCESS = 'USERCASE/SEND_SED/SUCCESS';
export const USERCASE_SEND_SED_REQUEST = 'USERCASE/SEND_SED/REQUEST';
export const USERCASE_SEND_SED_FAILURE = 'USERCASE/SEND_SED/FAILURE';

export const RINA_GET_URL_SUCCESS = 'RINA/GET_URL/SUCCESS';
export const RINA_GET_URL_REQUEST = 'RINA/GET_URL/REQUEST';
export const RINA_GET_URL_FAILURE = 'RINA/GET_URL/FAILURE';

export const USER_INFO_REQUEST = 'USER/INFO/REQUEST';
export const USER_INFO_SUCCESS = 'USER/INFO/SUCCESS';
export const USER_INFO_FAILURE = 'USER/INFO/FAILURE';

export const PDF_CLEAR            = 'PDF/CLEAR';
export const PDF_SELECTED         = 'PDF/SELECTED';
export const PDF_GENERATE_REQUEST = 'PDF/GENERATE/REQUEST';
export const PDF_GENERATE_SUCCESS = 'PDF/GENERATE/SUCCESS';
export const PDF_GENERATE_FAILURE = 'PDF/GENERATE/FAILURE';

export const PDF_LOADING_FILES_STARTED = 'PDF/LOADING_FILES/STARTED';
export const PDF_LOADING_FILES_FINISHED = 'PDF/LOADING_FILES/FINISHED';

export const PDF_SET_RECIPE       = 'PDF/SET_RECIPE';
export const PDF_SET_DND_TARGET   = 'PDF/SET_DND_TARGET';
export const PDF_SET_PAGE_SIZE    = 'PDF/SET_PAGE_SIZE';

export const PINFO_NEW                = 'PINFO/NEW';
export const PINFO_EVENT_SET_PROPERTY = 'PINFO/EVENT/SET_PROPERTY'

export const P4000_NEW                = 'P4000/NEW';
export const P4000_OPEN_SUCCESS       = 'P4000/OPEN/SUCCESS';
export const P4000_OPEN_FAILURE       = 'P4000/OPEN/FAILURE';
export const P4000_SUBMIT_REQUEST     = 'P4000/SUBMIT/REQUEST';
export const P4000_SUBMIT_SUCCESS     = 'P4000/SUBMIT/SUCCESS';
export const P4000_SUBMIT_FAILURE     = 'P4000/SUBMIT/FAILURE';
export const P4000_PAGE_SET           = 'P4000/PAGE/SET';
export const P4000_EVENT_ADD          = 'P4000/EVENT/ADD';
export const P4000_EVENT_REPLACE      = 'P4000/EVENT/REPLACE';
export const P4000_EVENT_EDIT_MODE    = 'P4000/EVENT/EDIT_MODE';
export const P4000_EVENT_DELETE       = 'P4000/EVENT/DELETE';
export const P4000_EVENT_CANCEL_EDIT  = 'P4000/EVENT/CANCEL_EDIT';
export const P4000_EVENT_SET_PROPERTY = 'P4000/EVENT/SET_PROPERTY';

export const PSELV_STEP_FORWARD       = 'PSELV/STEP/FORWARD';
export const PSELV_STEP_BACK          = 'PSELV/STEP/BACK';

