server:
    port: 8080

freg:
  security:
    oidc:
      ignored-paths: '/internal/**,/error**'
      refresh:
        enabled: 'true'
      auth:
        header-filter-enabled: 'false'
        cookie-filter-enabled: 'true'
      login:
        enabled: 'true'
      openam:
        url: '${OPENIDCONNECT_URL}'
      client-id: '${APP_NAME}-${FASIT_ENVIRONMENT_NAME}'
      client-secret: '${OPENIDCONNECTAGENT_PASSWORD}'

credential:
  username: '${SRVPENSJON_USERNAME}'
  password: '${SRVPENSJON_PASSWORD}'
