server:
    port: 8080

freg:
  security:
    oidc:
      ignored-paths: '/internal/**,/error**'
      refresh:
        enabled: 'true'
      auth:
        header-filter-enabled: 'false'
        cookie-filter-enabled: 'true'
      login:
        enabled: 'true'
      openam:
        url: '${OPENIDCONNECT_URL}'
      client-id: '${APP_NAME}-${FASIT_ENVIRONMENT_NAME}'
      client-secret: '${OPENIDCONNECTAGENT_PASSWORD}'

credential:
  username: '${SRVPENSJON_USERNAME}'
  password: '${SRVPENSJON_PASSWORD}'

eessibasis:
#  url: 'https://eux-app.nais.preprod.local'
  url: 'https://eux-app-t8.nais.preprod.local'

fagmodul:
  url: 'https://eessi-fagmodul.nais.preprod.local'
#  url: 'https://eessi-fagmodul-t8.nais.preprod.local'

rina:
   url: 'http://rina-oppl-utv004.adeo.no/portal/#/caseManagement/'