export const SERVER_OFFLINE = 'SERVER/OFFLINE';

export const LANGUAGE_CHANGED = 'LANGUAGE/CHANGED';

export const USERCASE_GET_CASE_SUCCESS = 'USERCASE/GET_CASE_SUCCESS';
export const USERCASE_GET_CASE_REQUEST = 'USERCASE/GET_CASE_REQUEST';
export const USERCASE_GET_CASE_FAILURE = 'USERCASE/GET_CASE_FAILURE';

export const USERCASE_GET_INSTITUTION_OPTIONS_SUCCESS = 'USERCASE/GET_INSTITUTION_OPTIONS_SUCCESS';
export const USERCASE_GET_INSTITUTION_OPTIONS_REQUEST = 'USERCASE/GET_INSTITUTION_OPTIONS_REQUEST';
export const USERCASE_GET_INSTITUTION_OPTIONS_FAILURE = 'USERCASE/GET_INSTITUTION_OPTIONS_FAILURE';

export const USERCASE_GET_BUC_OPTIONS_SUCCESS = 'USERCASE/GET_BUC_OPTIONS_SUCCESS';
export const USERCASE_GET_BUC_OPTIONS_REQUEST = 'USERCASE/GET_BUC_OPTIONS_REQUEST';
export const USERCASE_GET_BUC_OPTIONS_FAILURE = 'USERCASE/GET_BUC_OPTIONS_FAILURE';

export const USERCASE_GET_SED_OPTIONS_SUCCESS = 'USERCASE/GET_SED_OPTIONS_SUCCESS';
export const USERCASE_GET_SED_OPTIONS_REQUEST = 'USERCASE/GET_SED_OPTIONS_REQUEST';
export const USERCASE_GET_SED_OPTIONS_FAILURE = 'USERCASE/GET_SED_OPTIONS_FAILURE';

export const USERCASE_TO_CONFIRM_OPTIONS = 'USERCASE/TO_CONFIRM_OPTIONS';
export const USERCASE_TO_CONFIRM_CANCEL  = 'USERCASE/TO_CONFIRM_CANCEL';

export const USERCASE_POST_SUCCESS = 'USERCASE/POST_SUCCESS';
export const USERCASE_POST_REQUEST = 'USERCASE/POST_REQUEST';
export const USERCASE_POST_FAILURE = 'USERCASE/POST_FAILURE';

