export const SERVER_OFFLINE = 'SERVER_OFFLINE';

export const USERCASE_GET_CASE_SUCCESS = 'USERCASE_GET_CASE_SUCCESS';
export const USERCASE_GET_CASE_REQUEST = 'USERCASE_GET_CASE_REQUEST';
export const USERCASE_GET_CASE_FAILURE = 'USERCASE_GET_CASE_FAILURE';

export const USERCASE_GET_MOTTAGER_OPTIONS_SUCCESS = 'USERCASE_GET_MOTTAGER_OPTIONS_SUCCESS';
export const USERCASE_GET_MOTTAGER_OPTIONS_REQUEST = 'USERCASE_GET_MOTTAGER_OPTIONS_REQUEST';
export const USERCASE_GET_MOTTAGER_OPTIONS_FAILURE = 'USERCASE_GET_MOTTAGER_OPTIONS_FAILURE';

export const USERCASE_GET_BUC_OPTIONS_SUCCESS = 'USERCASE_GET_BUC_OPTIONS_SUCCESS';
export const USERCASE_GET_BUC_OPTIONS_REQUEST = 'USERCASE_GET_BUC_OPTIONS_REQUEST';
export const USERCASE_GET_BUC_OPTIONS_FAILURE = 'USERCASE_GET_BUC_OPTIONS_FAILURE';

export const USERCASE_GET_SED_OPTIONS_SUCCESS = 'USERCASE_GET_SED_OPTIONS_SUCCESS';
export const USERCASE_GET_SED_OPTIONS_REQUEST = 'USERCASE_GET_SED_OPTIONS_REQUEST';
export const USERCASE_GET_SED_OPTIONS_FAILURE = 'USERCASE_GET_SED_OPTIONS_FAILURE';

export const USERCASE_POST_SUCCESS = 'USERCASE_POST_SUCCESS';
export const USERCASE_POST_REQUEST = 'USERCASE_POST_REQUEST';
export const USERCASE_POST_FAILURE = 'USERCASE_POST_FAILURE';

