export const YTELSES_KOMPONENT_TYPER: Record<string, string> = {
  P_8_5_1_T: '8-5-1 Tillegg',
  AAP: 'Arbeidsavklaringspenger',
  AFP_KOMP_TILLEGG: 'AFP kompensasjonstillegg',
  AFP_KRONETILLEGG: 'AFP kronetillegg',
  AFP_LIVSVARIG: 'AFP livsvarig del',
  AFP_T: 'AFP tillegg',
  AP_GJT: 'Gjenlevendetillegg',
  AP_GJT_KAP19: 'Gjenlevendetillegg Kap19',
  DIFF_BER: 'Differanseberegning',
  ET: 'Ektefelletillegg',
  FAM_T: 'Familietillegg',
  FAST_UTGIFT_T: 'Tillegg faste utgifter',
  FREM_AFP_LIVSVARIG: 'Fremskrevet AFP livsvarig del',
  GAP: 'Garantipensjon',
  GAT: 'Garantitillegg',
  GP: 'Grunnpensjon',
  GT_EOS: 'Garantitillegg EØS Art 50',
  GT_NORDISK: 'Garantitillegg Nordisk Art 27',
  HJELP_BIDRAG: 'Hjelpeløshetsbidrag',
  HJELP_I_HUS: 'Tillegg til hjelp i huset',
  IP: 'Inntektspensjon',
  KRIG_GY: 'Krigspensjon og gammel yrkesskade',
  LIVS_AFP_OFFENTLIG: 'Livsvarig AFP offentlig',
  MENDEL: 'Mendel',
  MIN_NIVA_TILL_INDV: 'Minstenivåtillegg individuelt',
  MIN_NIVA_TILL_PPAR: 'Minstenivåtillegg pensjonistpar',
  PT: 'Pensjonstillegg',
  SKATT_F_GP: 'Skattefri grunnpensjon',
  SKATT_F_UT_ORDINER: 'Skattefri uføretrygd ordinær',
  SKJERMT: 'Skjermingstillegg',
  SP: 'Sykepenger',
  ST: 'Særtillegg',
  TFB: 'Barnetillegg fellesbarn',
  TP: 'Tilleggspensjon',
  TSB: 'Barnetillegg særkullsbarn',
  UFORETILLEGG_AP: 'Uforetillegg til alderspensjon',
  UT_AAP: 'Arbeidsavklaringspenger',
  UT_ET: 'Ektefelletillegg',
  UT_FAST_UTGIFT_T: 'Dekning av faste utgifter inst.opph',
  UT_GJT: 'Gjenlevendetillegg til uføretrygd',
  UT_GT_NORDISK: 'Garantitillegg Nordisk Art 27 UT',
  UT_ORDINER: 'Uføretrygd ordinær',
  UT_SP: 'Sykepenger',
  UT_TFB: 'Barnetillegg fellesbarn',
  UT_TSB: 'Barnetillegg særkullsbarn',
  VT: 'Ventetillegg'
}
