kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-frontend-ui-fss-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  env:
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: NAV_DEKORATOREN_URL
      value: https://www-q0.nav.no
    - name: ZONE
      value: fss
    - name: PUBLIC_WEBSOCKETURL
      value: https://eessi-pensjon-frontend-api-fss-q2.nais.preprod.local/
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-ui-fss.nais.preprod.local
    - https://pensjon-utland-q2.nais.preprod.local
  liveness:
    path: internal/isAlive
    port: 8080
    initialDelay: 45
  port: 8080
  prometheus:
    enabled: true
    path: internal/metrics
  readiness:
    path: internal/isReady
    port: 8080
    initialDelay: 45
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
