kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-frontend-ui-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  azure:
    sidecar:
      enabled: true
      autoLogin: false
    application:
      enabled: true
      claims:
        groups:
          - id: 6e921c7e-7b22-4c9a-9ff6-ee3719e3c4ba #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: 79c6b5b5-1144-495c-a2c9-78aebfb5faf4 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    outbound:
      external:
        - host: pensjon-utland-q2.intern.dev.nav.no
  env:
    - name: VITE_NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: VITE_EESSI_PENSJON_FRONTEND_API_URL
      value: {{eessi_pensjon_frontend_api_url}}
    - name: VITE_EESSI_PENSJON_FAGMODUL_URL
      value: {{eessi_pensjon_fagmodul_url}}
    - name: VITE_EESSI_PENSJON_FRONTEND_API_TOKEN_SCOPE
      value: {{eessi_pensjon_frontend_api_token_scope}}
    - name: VITE_EESSI_PENSJON_FAGMODUL_TOKEN_SCOPE
      value: {{eessi_pensjon_fagmodul_token_scope}}
  image: {{ image }}
  ingresses:
    - https://pensjon-utland-q2.intern.dev.nav.no
    - https://eessi-pensjon-frontend-ui-q2.intern.dev.nav.no
  liveness:
    path: internal/isAlive
    port: 8080
    initialDelay: 45
  port: 8080
  prometheus:
    enabled: true
    path: internal/metrics
  readiness:
    path: internal/isReady
    port: 8080
    initialDelay: 45
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
