kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-frontend-ui
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  env:
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: NAV_DEKORATOREN_URL
      value: https://www.nav.no
    - name: ZONE
      value: fss
    - name: PUBLIC_WEBSOCKETURL
      value: https://eessi-pensjon-frontend-api.intern.nav.no/
    - name: EESSI_PENSJON_FRONTEND_API_URL
      value: {{eessi_pensjon_frontend_api_url}}
    - name: EESSI_PENSJON_FAGMODUL_URL
      value: {{eessi_pensjon_fagmodul_url}}
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-frontend-ui.intern.nav.no
    - https://pensjon-utland.intern.nav.no
  liveness:
    path: internal/isAlive
    port: 8080
    initialDelay: 45
  port: 8080
  prometheus:
    enabled: true
    path: internal/metrics
  readiness:
    path: internal/isReady
    port: 8080
    initialDelay: 45
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
