kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-frontend-ui
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  azure:
    sidecar:
      enabled: true
      autoLogin: false
    application:
      enabled: true
      claims:
        groups:
          - id: 49d708e9-c141-4a01-9be9-aa539c48f1d2 #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: fedabd32-4cab-4307-ad69-ea24edc69790 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    outbound:
      external:
        - host: pensjon-utland.intern.nav.no

  env:
    - name: VITE_NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: VITE_EESSI_PENSJON_FRONTEND_API_URL
      value: {{eessi_pensjon_frontend_api_url}}
    - name: VITE_EESSI_PENSJON_FAGMODUL_URL
      value: {{eessi_pensjon_fagmodul_url}}
    - name: VITE_EESSI_PENSJON_FRONTEND_API_TOKEN_SCOPE
      value: {{eessi_pensjon_frontend_api_token_scope}}
    - name: VITE_EESSI_PENSJON_FAGMODUL_TOKEN_SCOPE
      value: {{eessi_pensjon_fagmodul_token_scope}}
  image: {{ image }}
  ingresses:
    - https://pensjon-utland.intern.nav.no
    - https://eessi-pensjon-frontend-ui.intern.nav.no
  liveness:
    path: internal/isAlive
    port: 8080
    initialDelay: 45
  port: 8080
  prometheus:
    enabled: true
    path: internal/metrics
  readiness:
    path: internal/isReady
    port: 8080
    initialDelay: 45
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
