eessi_pensjon_frontend_api_fss_url: http://eessi-pensjon-frontend-api-fss
eessi_pensjon_fagmodul_url: http://eessi-pensjon-fagmodul
eessi_pensjon_fagmodul_decorator_url: http://eessi-pensjon-fagmodul
