eessi_pensjon_frontend_api_url: https://eessi-pensjon-frontend-api.intern.nav.no
eessi_pensjon_fagmodul_url: https://eessi-pensjon-fagmodul.intern.nav.no
eessi_pensjon_frontend_api_token_scope: api://prod-gcp.eessipensjon.eessi-pensjon-frontend-api/.default
eessi_pensjon_fagmodul_token_scope: api://prod-gcp.eessipensjon.eessi-pensjon-fagmodul/.default
