name: Build, push, and deploy

on:
  push:
    branches:
      - feature/naiseratorOvergang
jobs:
  tag_build_and_deploy:
    name: 'Build, push, and deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # OPPRETTER GIT TAG
      - name: 'Bump version and push tag'
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: .*

      # HENTER NYESTE TAG FOR Å BRUKE DET SOM VERSJONSNUMMER
      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # OPPRETTER IMAGE VARIABEL MED VERSJONSNUMMER
      - name: 'Set Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-saksbehandling-ui:${{ steps.previoustag.outputs.tag }}"

      # SETTER OPP NODE
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # BYGGER APP
      - name: 'Bygg'
        run: |
          npm install
          npm audit --json
          npm run build

      # BYGGER DOCKER CONTAINER
      - name: 'Build and publish Docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${{ env.IMAGE }}

      # DEPLOYER TIL NAIS
      - name: 'Deploy to NAIS'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q2.yml
          IMAGE: ${{ env.IMAGE }}


