name: Build, push, and deploy

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  tag_build_and_deploy:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

      - name: 'Pull repo'
        uses: actions/checkout@v1

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Setter Image'
        run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-frontend-ui-fss:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Bygg'
        run: |
          npm install
          npm run build:css
          npm run build

      - name: 'Build and publish Docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker build --tag ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}
