name: Build, push, and deploy

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  tag_build_and_deploy:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # SETTER OPP NODE
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # BYGGER APP
      - name: 'Bygg'
        run: |
          npm install
          npm run build:css
          npm run test:ci
          npm run build
